# Generated by Django 5.0.3 on 2024-03-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=128)),
                ('driver_name', models.CharField(max_length=128)),
                ('commentary', models.TextField(blank=True, max_length=256, null=True)),
                ('client_list', models.TextField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dispatcher', models.CharField(choices=[('Ксения Майорова', 'Ксения Майорова'), ('Мазалов Максим', 'Мазалов Максим'), ('Тольев Алексей', 'Тольев Алексей'), ('Анна Нуруллова', 'Анна Нуруллова')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EmailReportToClientSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=128)),
                ('message', models.TextField(blank=True, max_length=2048, null=True)),
                ('date', models.CharField(blank=True, max_length=64, null=True)),
                ('clients', models.ManyToManyField(to='manager_client.client')),
            ],
        ),
    ]
