# Generated by Django 5.0.3 on 2024-03-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0002_alter_deliveryreport_client_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='client_list',
            field=models.TextField(choices=[('тэк правильный выбор', 'тэк правильный выбор'), ('останкино', 'останкино'), ('ярославский бройлер', 'ярославский бройлер')], max_length=256),
        ),
    ]
