# Generated by Django 5.0.3 on 2024-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0003_alter_deliveryreport_client_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='client_list',
            field=models.TextField(max_length=256),
        ),
    ]
