# Generated by Django 5.0.3 on 2024-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_car_data', '0002_alter_uploadtrailerdata_trailer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcardata',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadtrailerdata',
            name='trailer_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='uploadtrailerdata',
            name='trailer_number',
            field=models.CharField(max_length=48),
        ),
    ]
