# Generated by Django 5.0.3 on 2024-03-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contacts', models.TextField(max_length=700)),
                ('main_email', models.CharField(blank=True, max_length=1000, null=True)),
                ('manager', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_client.manager')),
            ],
        ),
    ]
